### ISSUE TITLE
nedd a help

### ISSUE THREAD

**Issue by arsewizz** [msach22/opentok-ionic-samples#1]
Hi, thaks for the repo but i have a question. in my application i want to be able to call from user A to user B !!! e.g : test@github.com to call user@github.com, possible to do it ?

**Comment by LawrenceByrd** [comment]
The OpenTok platform provides all the live video capabilities but does not manage user/customer identities and how different users get "connected". This is expected to be handled in your own application where you are managing users. So your app needs to decide that A and B need to talk and then your app creates an OpenTok session object and tells each client to join that session. See https://tokbox.com/developer/guides/basics/. I believe you will find this of all WebRTC type platforms - they don't assume any model of user identity and connectivity but allow your app to define this. Some apps, like conferencing apps, often don't use a "calling" model but have users meet in a "room" or at a "URL". Other apps, maybe yours, may want to use a user-based Skype-like calling mechanism which is then part of how your app works.

**Comment by LawrenceByrd** [comment]
Mobile apps, for example, often use something like Google Firebase https://firebase.google.com to manage a common database of users with authentication etc. that would then support your app distinguishing user A from user B, allowing them to find each other as appropriate, and then arranging a "call". Firebase might also be used to monitor the availability-status of your users, whether they can be called etc. Once you have determined that A and B should talk, and you put them both into an OpenTok session, then OpenTok does provide a real-time signaling layer that might be used for alerts back and forth - see https://tokbox.com/developer/guides/signaling.

**Comment by msach22** [comment]
@LawrenceByrd thanks for answering, I think its safe to close the issue.
